From 3acb5c2d0ff8c8e19749a999e88897c8a57a40aa Mon Sep 17 00:00:00 2001
From: "H. Vetinari" <h.vetinari@gmx.com>
Date: Wed, 22 May 2024 08:53:03 +1100
Subject: [PATCH 3/3] increase timeout in
 TestThreadedCSVTableRead::test_cancellation

---
 python/pyarrow/tests/test_csv.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/python/pyarrow/tests/test_csv.py b/python/pyarrow/tests/test_csv.py
index bc1dd8a09..9ddb5197e 100644
--- a/python/pyarrow/tests/test_csv.py
+++ b/python/pyarrow/tests/test_csv.py
@@ -1470,7 +1470,7 @@ class BaseCSVTableRead(BaseTestCSV):
             pytest.fail("Failed to get an interruption during CSV reading")
 
         # Interruption should have arrived timely
-        assert last_duration <= 1.0
+        assert last_duration <= 2.0
         e = exc_info.__context__
         assert isinstance(e, pa.ArrowCancelled)
         assert e.signum == signum
